name: Security Testing Build

# Build a multi-arch docker image for testing security updates to SWIRL

on:
  push:
    # only trigger on branches to security-testing, not on tags
    branches: 'security-testing'


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: pull preview UI image
      run: docker pull swirlai/spyglass:preview
    - name: builder bootstrap
      run: docker buildx create --name devBuilder --use --bootstrap
    - name: Build the Docker image
      run: docker buildx build -t swirlai/swirl-search:security-testing --platform linux/amd64,linux/arm64 --push .
