name: UnitTests

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - 'README.md'
      - 'Gemfile'
      - 'Gemfile.lock'
    # only trigger on branches, not on tags
    branches: 'main'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
            python-version: '3.10'
            cache: 'pip' # caching pip stuff
    - name: Run Install Swirl
      run: ./install.sh
    - name: Run Install Tests Swirl
      run: ./install-test.sh
    - name: Run pytest unit tests
      run: pytest
